version: "3.9"
services:

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    image: daynchu/buy_sim_app:1.0.0
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env.production      # <— aquí
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app                     # opcional: para desarrollo

volumes:
  db_data:
